services:
  - type: web
    name: exam-system-backend
    env: python
    plan: free
    buildCommand: pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: exam_system
      - key: BASE_URL
        sync: false
      - key: FRONTEND_BASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false


